version: '3.8'
services:
  # 1. 데이터베이스 컨테이너
  postgres-db: # 서비스 명 - 컨테이너 통신 및 도커 컴포즈 명령어
    image: postgres:latest # 이미지 : 버전
    container_name: postgres_container # 컨테이너 이름. 
    environment:
      POSTGRES_USER:  # 관리자 계정 
      POSTGRES_PASSWORD:  # 관리자 password
      POSTGRES_DB:  # 초기 DB 이름
    ports:
      - "5432:5432" # 포트 포워딩
    volumes:
      - pgdata:/var/lib/postgresql/data # 저장 위치
    networks:
      - my-network # 네트워크 명

volumes:
  pgdata:

networks:
  my-network:
    driver: bridge