version: '3.8'
services:
  # 1. 데이터베이스 컨테이너
  postgres-db: # 서비스 명 - 컨테이너 통신 및 도커 컴포즈 명령어
    image: postgres:15 # 이미지 : 버전
    container_name: postgres_db # 컨테이너 이름. 
    env_file:
      - .env
    environment: # .env 파일에서 환경 변수값 호출
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432" # 포트 포워딩
    volumes:
      - pgdata:/var/lib/postgresql/data # 저장 위치
    networks:
      - my-network # 네트워크 명

volumes:
  pgdata:

networks:
  my-network:
    driver: bridge